### ISSUE TITLE
Question - config file

### ISSUE THREAD

**Issue by SupercudakPl** [Mikusch/LethalSkullEnemy#2]
Hi, sorry for asking you this way, but I didn't know how else can I reach you. 

I saw in the changelog on the Thunderstore page you said that you're going to look into adding a config file. I was just wondering if you have an estimated release date of an update with it. 
I don't want to push you or something like that, I am just curious. I would love to spice up the spawn rate of the enemy because I wasn't able to find it yet. 

Again, sorry for reaching out like this and bugging you about it. I hope everything is ok.

**Comment by Mikusch** [comment]
Hey, have quite a lot to do, but I can try adding it in the next week or so. Planned config options are spawn rates and some other miscellaneous settings like speed

**Comment by SupercudakPl** [comment]
I'm sorry. I don't want to pressure you to do something when you don't have time. I just wanted to know something about it because the last update was almost a month ago and I was curious. If you don't have time for this, don't do it. When you will have time and want, add it, but if you don't just ignore it and focus on your life.

**Comment by Mikusch** [comment]
I've added a config with the latest release, let me know if you need anything else

**Comment by SupercudakPl** [comment]
Thank you
